### ISSUE TITLE
self_contained=FALSE unexpected behavior

### ISSUE THREAD

**Issue by hrbrmstr** [hrbrmstr/markdowntemplates#3]
a commenter on the blog mentioned that there's weird behavior when `self_contained=FALSE` is used. need to poke at this.

**Comment by mwhitaker** [comment]
Commenter here! I think what I saw is normal behavior in the `rmarkdown` package. Just tried it with the [built-in Package Vignette template](https://gist.github.com/mwhitaker/da925d409ad30242f5f7) and the same thing happens when you knit the Rmd file, where the css file is linked to where the package is installed. I would personally prefer to have both js and css files in a lib_dir folder that can be specified, but could just use a simple gulpfile in the workflow to move some stuff around.
